version: 2

models:
  - name: fact_sales
    columns:
      - name: sale_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: product_id
        tests:
          - relationships:
              to: ref('dim_products')
              field: product_id

  - name: final_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: final_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null